"""
Django settings for googleTech project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os 
import mimetypes
import dj_database_url
mimetypes.add_type("application/javascript", ".js", True)

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+o-_h*=5@xo)v6popvxw6pt(q#w=pgplh#^o4s0-!1ozp=6-%s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compte',
    'cours',
    'quiz',
    'forum',
    #'debug_toolbar',
    'django_extensions',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'compte.middleware.MaintenanceMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    #'debug_toolbar.middleware.DebugToolbardMiddleware',

]

STATICFILES_STORAGE = 'whitenoise.staorage.CompressdManifestStaticFilesStorage'

ROOT_URLCONF = 'googleTech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'googleTech.wsgi.application'
ASGI_APPLICATION = 'googleTech.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.Layers.InMemoryChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



# … autres configs …

# Base de données : PostgreSQL en production, SQLite en développement
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join('DATABASE_URL', 'db.sqlite3'),
        conn_max_age=600,
        ssl_require=True
    )
}

# Fichiers statiques (WhiteNoise)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # … les autres middlewares …
]

# Hôtes autorisés
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1').split(',')

# Sécurité (désactivée en développement local)
if not os.environ.get('DJANGO_DEBUG', 'True') == 'True':
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'compte.Utilisateur'
ENSEIGNANT_SECRET_CODE = "Tech2026"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake', 
    }
}

CONN_MAX_AGE = 600 # secondes (10 minutes)



DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'   # en dev

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',  # n'enregistre que les avertissements et erreurs
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

"""
if DEBUG:
    # Afficher la barre seulement pour les requêtes locales
    INTERNAL_IPS = ['127.0.0.1', 'localhost', "::1"] 

    # Optionnel : rendre la barre moins gênante
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'googleTech.debug_toolbar_callback.show_toolbar', # toujours en debug
        'INTERCEPT_REDIRECTS': False,                   # ne pas bloquer les redirections
        'ENABLE_STACKTRACES': False,                    # plus léger
        'JQUERY_URL': '',                               # utiliser jQuery déjà présent
        'SHOW_COLLAPSED': True,                         # panneaux repliés par défaut
    }
"""

from django.conf import settings
def masquer_djdt_complet(request):
    # Liste des pages spécifiques à masquer
    pages_a_masquer = [
        '/',                  # Accueil
        '/confidentialite/',  # Page de confidentialité (à adapter selon votre URL)
    ]
    
    # 1. On masque si l'URL est l'accueil ou la confidentialité
    if request.path in pages_a_masquer:
        return False
        
    # 2. On masque si l'URL appartient à toute l'application compte
    if request.path.startswith('/compte/'):
        return False
        
    # Sinon, on l'affiche uniquement si DEBUG est actif
    from django.conf import settings
    return settings.DEBUG

# Configuration de la toolbar
DEBUG_TOOLBAR_CONFIG = {
    # On passe la fonction sous forme de texte pour éviter le bug d'import circulaire WSGI
    'SHOW_TOOLBAR_CALLBACK': masquer_djdt_complet,
}

DATA_UPLOAD_MAX_MEMORY_SISE = 5 * 1024 * 1024 # 5 Mo

# Session sécurisées, cela aide à renforncer la sécuritée en developpement
SESSION_COOKIE_HTTPONLY = True      # Empêche l'accès JavaScript au cookie de session (par défaut True)
SESSION_COOKIE_SAMESITE = 'Lax'     # Protège contre les attaques CSRF
CSRF_COOKIE_HTTPONLY = True         # Recommandé, mais pas obligatoire (False par défaut, mais True est plus sûr)
SESSION_COOKIE_SECURE = False       # En HTTP, doit être False (car HTTPS n'est pas actif)
CSRF_COOKIE_SECURE = False

SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True   # Renouvelle le cookie à chaque requête

# Code secret de l'enseignant
import os
ENSEIGNANT_SECRET_CODE = os.environ.get('ENSEIGNANT_SECRET_CODE', 'Teach2026')  # Valeur par défaut pour le développement

LOGIN_URL = 'login'

if not DEBUG:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = 'eu-west-1'  # adaptez
    AWS_DEFAULT_ACL = None
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# Stockage distant des sauvegardes (S3)
BACKUP_S3_ACCESS_KEY = os.environ.get('BACKUP_S3_ACCESS_KEY', '')
BACKUP_S3_SECRET_KEY = os.environ.get('BACKUP_S3_SECRET_KEY', '')
BACKUP_S3_BUCKET_NAME = os.environ.get('BACKUP_S3_BUCKET_NAME', 'google-tech-backups')
BACKUP_S3_REGION = os.environ.get('BACKUP_S3_REGION', 'eu-west-1')
BACKUP_S3_ENDPOINT_URL = os.environ.get('BACKUP_S3_ENDPOINT_URL', None)  # pour les services non-AWS

# Configuration de des API 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # pour l'instant
        'rest_framework.authentication.TokenAuthentication',    # pour les applis mobiles plus tard
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@google-tech.com')

